name: Ansible_Install
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: test
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: |
          sudo apt-get update
          sudo apt-add-repository ppa:ansible/ansible
          sudo apt-get update 
           sudo apt-get install ansible -y 
